import {Roboto} from 'next/font/google'
import "./globals.css";
import Navbar from '../components/shared/Navbar'


const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
       <Navbar/>
        {children}
        </body>
    </html>
  );
}
